from typing import overload

class PulchraResult:
    pdb_str: str
    traj_pdb_str: str
    @overload
    def __init__(self, _pdb_str: str, _traj_pdb_str: str) -> None: ...
    @overload
    def __init__(self, arg0: PulchraResult) -> None: ...
    def assign(self) -> PulchraResult: ...

def run_from_pdb_str(pdb_str: str) -> PulchraResult: ...
