---
name: Pip
'on':
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
env:
  FORCE_COLOR: 3
concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        python-version:
          - '3.8'
          - '3.11'
          - '3.12'
          - pypy-3.8
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build and install
      run: pip install --verbose .
    - name: Test
      run: python src/python/tests/test.py
